import { Lato } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/utils/NavbarWrapper";
import ThemeProviderWrapper from "@/utils/ThemeProviderWrapper";
import { cookies } from "next/headers";

const lato = Lato({
    variable: "--font-lato",
    subsets: ["latin"],
    weight: ["100", "300", "400", "700", "900"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const cookieStore = await cookies();
    const initialTheme = cookieStore.get('theme')?.value || 'light';   
    return (
        <html lang="en" className={initialTheme === 'dark' ? 'dark' : undefined}>
            <body
                className={`${lato.variable} antialiased`}
            >
                <ThemeProviderWrapper initialTheme={initialTheme}>
                    <NavbarWrapper>
                        {children}
                    </NavbarWrapper>
                </ThemeProviderWrapper>
            </body>
        </html>
    );
}
